indexing-settings:
  sites:
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
    - url: https://itdeti.ru
      name: ItDeti.ru
    - url: https://hacker-son.com
      name: Hacker-son
#    - url: https://gkb15.moscow/
#      name: GBK15
#    - url: https://lenta.ru
#      name: Lenta.ru
#    - url: https://et-cetera.ru
#      name: Et-cetera
#    - url: https://shcool11-balakhna.edusite.ru
#      name: BalakhnaSchool11
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_NAME}:5432/search_engine
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          show_sql: true
          format_sql: true
        order_updates: true
server:
  port: 8080
