indexing-settings:
  sites:
    #    - url: https://sendel.ru
    #      name: Sendel.ru
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
    - url: https://itdeti.ru
      name: ItDeti.ru
    - url: https://hacker-son.com
      name: Hacker-son
    - url: https://gkb15.moscow/
      name: GBK15
#    - url: https://lenta.ru
#      name: Lenta.ru
#    - url: https://et-cetera.ru
#      name: Et-cetera
#    - url: https://skillbox.ru/
#      name: Skillbox
#    - url: https://shcool11-balakhna.edusite.ru
#      name: BalakhnaSchool11
spring:
  profiles:
    active: logging
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine
    password: 1234
    username: roman
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_updates: true
        format_sql: false
        show_sql: false

server:
  port: 8080
